'on':
    schedule:
      - cron: 0 6 * * 1-5
    workflow_dispatch: {}
name: Preview
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M')"
      - name: Start new release cycle
        run: |2-

                  version=`cat package.json | jq -r .version`
                  echo "Current version: $version"
                  echo "CURRENT_VERSION=${version}" >> $GITHUB_ENV
                  
      - uses: actions/create-release@v1
        id: githubCreateRelease
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          body: '${{ env.CURRENT_VERSION }}_PREVIEW_${{ steps.date.outputs.date }}'
          release_name: '${{ env.CURRENT_VERSION }}_PREVIEW_${{ steps.date.outputs.date }}'
          tag_name: '${{ env.CURRENT_VERSION }}_PREVIEW_${{ steps.date.outputs.date }}'
          prerelease: true
