'on':
    schedule:
      - cron: 0 5 * * 1-5
    workflow_dispatch: {}
name: Preview Check
jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/checkout@v2
      - name: Get latest prerelease
        id: latestPrereleaseHash
        run: |2-

              git fetch --tags
              tagname=`git tag --list '*_PREVIEW_*' | tail -1`
              echo $tagname
              commitHash=`git show-ref ${tagname} | awk '{print $1}'`
              echo $commitHash
              echo "PRERELEASE_COMMIT_HASH=$commitHash" >> $GITHUB_ENV 
      - name: Trigger Preview Workflow
        if: ${{ github.sha }} != ${{ steps.latestPrereleaseHash.outputs.latestPrereleaseHash }}
        run: |2-
              echo ${{ github.sha }}
              echo ${{ steps.latestPrereleaseHash.outputs.latestPrereleaseHash }}
              curl \
                -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.PAC }}" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/preview.yml/dispatches \
                -d '{"ref":"master"}'