'on':
    schedule:
      - cron: "*/5 * * * *"
    workflow_dispatch: {}
name: Preview
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build-and-test
      - static-code-analysis
    steps:
      - uses: actions/create-release@v1
        id: githubCreateRelease
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          body: 'testbody'
          tag_name: 'testTAG'
          release_name: 'testRELEASENAME'