'on':
    schedule:
      - cron: 0 5 * * 1-5
    workflow_dispatch: {}
name: Preview Check
jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      IS_COMMIT_EQUAL: '${{steps.isCommitHashEqual.outputs.isCommitHashEqual}}'
    timeout-minutes: 10
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M')"
      - name: Get latest prerelease
        id: latestPrereleaseHash
        run: |2-

              git fetch --tags
              tagname=`git tag --list '*_PREVIEW_*' | tail -1`
              echo $tagname
              commitHash=`git show-ref ${tagname} | awk '{print $1}'`
              echo $commitHash
              echo "PRERELEASE_COMMIT_HASH=$commitHash" >> $GITHUB_ENV 
      - name: Compare commit hashes
        id: isCommitHashEqual
        env:
          CURRENT_COMMIT_HASH: '${{ github.sha }}'
        run: |2-
              echo $PRERELEASE_COMMIT_HASH
              echo $CURRENT_COMMIT_HASH
              if [ "$PRERELEASE_COMMIT_HASH" = "$CURRENT_COMMIT_HASH" ]; then
                  echo "::set-output name=isCommitHashEqual::true"
              else
                  echo "::set-output name=isCommitHashEqual::false"
              fi
              echo $IS_COMMIT_EQUAL
      - name: Trigger Preview Workflow
        if: steps.isCommitHashEqual.outputs.isCommitHashEqual != 'true'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |2-
              curl \
                -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.PAC }}" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/preview.yml/dispatches \
                -d '{"ref":"master"}'