'on':
    schedule:
      - cron: "*/5 * * * *"
    workflow_dispatch: {}
name: Preview
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/create-release@v1
        id: githubCreateRelease
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          body: 'testbody'
          tag_name: 'testTAG'
          release_name: 'testRELEASENAME'